language: node_js
node_js:
  - "8"
install:
  - npm install
before_script:
  - npm install -g sequelize-cli
script:
  - npm run server:test
  - npm run server:coverage
  - npm run client:test
  - npm run client:coverage
