export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_GROUPS = 'SET_GROUPS';
export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP';
